# 指定 Actions 的名稱，會顯示在 Actions 頁面上
name: Deploy on EC2

# 指定觸發的事件(trigger event)，這裡是 push 到 main 分支時觸發
on:
  pull_request:
    branches: main
    types: closed

# 指定工作流程(jobs)
# 每個 actions 至少要有一個 job
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - run: echo "This job was tirggered by a ${{ github.event_name }} event"
        - name: checkout-repository
          uses: actions/checkout@v4
        - name: Run SSH commands
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_KEY }}
            port: ${{ secrets.EC2_PORT }}
            script: |
                echo "Connected to EC2"
                cd /home/ubuntu/cicd-pipeline-workshop
                git pull
                git checkout phase1
                pm2 restart src/server.js

