name: manual input

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was tirggered by a ${{ github.event_name }} event"
      # 使用 actions/checkout 來 checkout repository
      # 可能需要進行後續編譯或測試之類的
      - run: echo "input logLevel - ${{ inputs.logLevel }}"
        