# 指定 Actions 的名稱，會顯示在 Actions 頁面上
name: Test when PR

# 指定觸發的事件(trigger event)，這裡是 push 到 main 分支時觸發
on:
  pull_request:
    branches: main

# 指定工作流程(jobs)
# 每個 actions 至少要有一個 job
jobs:
  syntax-check:
    # 指定運行環境，可以多個
    runs-on: ubuntu-latest
    steps:
        - run: echo "This job was tirggered by a ${{ github.event_name }} event"

        - name: checkout-repository
          uses: actions/checkout@v4
        
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
    
        - name: Cache Node.js and npm
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: ${{ runner.os }}-node-
        
        - name: Install dependencies if cache missed
          run: test -d node_modules && echo "node_modules exists" || npm install
  
        - name: Lint check
          run: ./node_modules/.bin/eslint .

        - name: Prettier check
          run: ./node_modules/.bin/prettier --write .

  test-code:
    runs-on: ubuntu-latest
    needs: syntax-check
    steps:
        - name: checkout-repository
          uses: actions/checkout@v4
      
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
  
        - name: Cache Node.js and npm
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: ${{ runner.os }}-node-
        
        - name: Install dependencies if cache missed
          run: test -d node_modules && echo "node_modules exists" || npm install

        - name: Run Mocha tests with nyc and mochawesome
          run: |
            ./node_modules/.bin/nyc --reporter=html ./node_modules/.bin/mocha --reporter mochawesome

        - name: Upload mochawesome report
          uses: actions/upload-artifact@v2
          with:
            name: mochawesome-report
            path: ./mochawesome-report

        - name: Upload code coverage report
          uses: actions/upload-artifact@v2
          with:
            name: code-coverage-report
            path: ./coverage